import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { Footer, Navigation } from "@/components";
import "./global.css";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid grid-cols-[1fr_250px]`}>
        <section className="bg-blue-100 flex flex-col border-r-2 border-black relative">
          <Navigation />
          <div className="bg-lime-100 h-screen">{children}</div>
          <Footer />
        </section>
        <section className="bg-green-100">
          <nav className="sticky top-0">
            <ul>
              <li>blog article 1</li>
              <li>blog article 2</li>
              <li>blog article 3</li>
            </ul>
          </nav>
        </section>
      </body>
    </html>
  );
}
